create table public.practice_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  exercise_id uuid not null references public.exercises on delete cascade,
  duration integer not null, -- in seconds
  max_bpm integer,
  created_at timestamp with time zone not null default now()
);

alter table public.practice_log enable row level security;

create policy "Users can view their own practice logs."
  on public.practice_log for select
  using ( (select auth.uid()) = user_id );

create policy "Users can insert their own practice logs."
  on public.practice_log for insert
  with check ( (select auth.uid()) = user_id );