-- Custom types
create type public.app_role as enum ('admin', 'user');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      app_role not null default 'user',
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- inserts a row into public.user_roles
create function public.handle_new_user_role()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.user_roles (user_id, role)
  values (new.id, 'user');
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created_add_role
  after insert on auth.users
  for each row execute procedure public.handle_new_user_role();