CREATE TABLE public.lessons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.lesson_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id UUID NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  scale_id UUID REFERENCES public.scales(id) ON DELETE CASCADE,
  scale_shape_id UUID REFERENCES public.scale_shapes(id) ON DELETE CASCADE,
  target_bpm INTEGER,
  "order" INTEGER NOT NULL
);

ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_exercises ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own lessons."
  ON public.lessons FOR SELECT
  USING ( (select auth.uid()) = created_by );

CREATE POLICY "Users can insert their own lessons."
  ON public.lessons FOR INSERT
  WITH CHECK ( (select auth.uid()) = created_by );

CREATE POLICY "Users can view their own lesson exercises."
  ON public.lesson_exercises FOR SELECT
  USING ( (select auth.uid()) = (SELECT created_by FROM lessons WHERE id = lesson_id) );

CREATE POLICY "Users can insert their own lesson exercises."
  ON public.lesson_exercises FOR INSERT
  WITH CHECK ( (select auth.uid()) = (SELECT created_by FROM lessons WHERE id = lesson_id) );