// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idsufbsfywgmcrhldqxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkc3VmYnNmeXdnbWNyaGxkcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTIyMDIsImV4cCI6MjA3MDQ4ODIwMn0.7hmo5b0t4AtzQx6gZU2WK7c_IwnvcgCwW-D_qIGLlW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});